#+TITLE:Munkres Problem 27.5
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>
#+HTML_HEAD: <style> body {font-size:15px;} </style>

Given some open set $U$ such that $U \cap \cup_{n} A_n = U \cap A \neq \emptyset$, our strategy is to construct a sequence of sets in $U$ which imply the existence of a point of $U$ not lying in $A$.

Clearly, $U \not\subset A_1$, as $\text{Int}(A_1) = \emptyset$. Therefore, we can choose a point $x_1$ such that $x_1 \in U$ and $x_1 \notin A_1$. From here, since $X$ is compact Hausdorff, we can choose
open neighbourhood $V_1$ and $W_1$ which are disjoint, where $V_1$ contains $x_1$ and $W_1$ contains the compact subspace $(X - U) \cup A_1$, as it is closed. Thus, $V_1$ is in the closed set $X - W_1$, which is in $U$.

Thus, $x_1 \in V_1 \subset \overline{V}_1 \subset U$, and $\overline{V}_1$ is disjoint from $A_1$.

We repeat this protocol inductively, with $V_1$ taking the place of $U$, and $A_2$ taking the place of $A_1$, then $V_n$ taking the place of $V_{n - 1}$ and $A_{n + 1}$ replacing $A_n$. This yields a set of nested closed sets $\overline{V}_n$
which posses the finite intersection property. Since the space is compact, their infinite intersection must be non-empty, containing some $x$. Clearly, $x \notin A_n$ for any $A_n$, by construction of the above sequence.

Thus, $U \not\subset A$, and $\text{Int}(A)$ must be the empty set.
