#+TITLE:Lee Problem 1.1
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>
#+HTML_HEAD: <style> body {font-size:15px;} </style>

Let $X^{\pm} = \{(x, \pm 1) \ | \ x \in \mathbb{R}\}$. Clearly, $X = X^{+} \cup X^{-}$. Let $X/\sim$ be the quotient space, which is topologized
by taking the set of all $U$ such that $\pi^{-1}(U)$ is open in $X$ as a subspace of $\mathbb{R}^2$ ($\pi$ is the quotient map).

For each equivalence class in $X/\sim$ containing $(x, \pm 1)$, identify this class with $x \in \mathbb{R}$. We let $\mathcal{B}$ be the collection
of all open balls centred at rational $x$ with rational radius, not containing $0$ (so the notion of an open ball is well-defined under our identification).
Clearly, the inverse image under $\pi^{-1}$ for any of these sets is open in $X$.

Let $\mathcal{B}'$ be the collection of all open balls of rational radius centred at $(0, 1)$ and $(0, -1)$, individually. Note that
the inverse image under $\pi^{-1}$ for these sets will be open as well:

$$\pi^{-1}(B_r((0, \pm 1))) = (-r, r) \times \{\pm 1\} \cup \left( (-r, 0) \cup (0, r) \right) \times \{\mp 1\}$$

Of course, $\mathcal{B} \cup \mathcal{B}'$ is countable. It is also a basis for the topology: each element of the basis is open in the quotient topology as we have shown,
and in addition, given a generic element of the topology, $U$ with $\pi^{-1}(U)$ open in $X$, note that $\pi^{-1}(U)$ can be written as a union of rational-radius balls
centred at points along the two copies of $\mathbb{R}$ not containing $0$, as well as rational-radius balls centred at $0$. $\pi$ clearly sends these elements to elements
of $\mathcal{B} \cup \mathcal{B}'$, so $\pi(\pi^{-1}(U)) = U$ (as $\pi$ is surjective) is a union of elements of the countable set $\mathcal{B} \cup \mathcal{B}'$.

It follows immediately that $\mathcal{B} \cup \mathcal{B}'$ is a countable basis for the quotient topology.

This space is also clearly locally Euclidean: the charts sending the two open sets $U_{\pm} = \{ x \neq 0 \} \cup (0, \pm 1)$ to their projection onto the
first coordinate are homeomorphisms $\varphi_{\pm} U_{\pm} \rightarrow \mathbb{R}$.

Finally, note that the space is not Hausdorff. Suppose $V_{\pm}$ are open sets about $(0, \pm 1)$, so $\pi^{-1}(V_{\pm})$ are open in $X$. Then the
$\pi^{-1}(V_{\pm})$ must each contain some interval $(-\varepsilon, \varepsilon) \cup \{ \pm 1\}$
respectively: but then $V_{+} \cap V_{-} \neq \emptyset$.
